---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.1
    hooks:
      - id: pyupgrade
        args:
          - "--py37-plus"
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--application-directories=.:Django"
        exclude: migrations
  - repo: https://github.com/asottile/yesqa
    rev: v0.0.11
    hooks:
      - id: yesqa
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        exclude: migrations
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
